#!/bin/bash

RESET="\033[0m"
BOLD="\033[1m"
RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[1;34m"

DEP_OK="${GREEN}OK${RESET}"
DEP_NO="${RED}NO${RESET}"

DEP_PASS=true

nocheck="--no-check"
nodb="--no-db"

echo -e "\n${BOLD}Welcome to the Smartkeg build process!${RESET}"

if [ "$1" != "$nocheck" ] && [ "$2" != "$nocheck" ];
then
    echo -e "${BLUE}=>${RESET} Checking Dependencies\n"
    echo -ne "\tMySQL           "
    # MySQL
    if command -v mysql > /dev/null;
    then
        echo -e $DEP_OK
    else
        DEP_PASS=false
        echo -e $DEP_NO
    fi

    # pip
    echo -ne "\tpip             "
    if command -v pip2 > /dev/null;
    then
        echo -e $DEP_OK

        # MySQLdb
        echo -ne "\tMySQLdb         "
        if pip2 list | grep MySQL-python > /dev/null;
        then
            echo -e $DEP_OK
        else
            DEP_PASS=false
            echo -e $DEP_NO
        fi

        # RPi.GPIO
        echo -ne "\tRPi.GPIO        "
        if pip2 list | grep RPi.GPIO > /dev/null;
        then
            echo -e $DEP_OK
        else
            DEP_PASS=false
            echo -e $DEP_NO
        fi
    else
        DEP_PASS=false
        echo -e $DEP_NO
    fi


    if [ !"$DEP_PASS" ];
    then
        echo -e "\n${RED}Warning!${RESET}: One or more dependencies are not installed on your system.  The Smartkeg software may act erroneously without the required libraries.  Please ensure they are installed before attempting to execute the Smartkeg Consumption Monitoring System."
    fi
fi

if [ "$1" != "$nodb" ] && [ "$2" != "$nodb" ];
then
    echo -e "\n${BLUE}=>${RESET} Configuring Database\n"
    echo -e "\tCreate user"
    echo -e "\tCreate tables"
    echo -e "\tInsert defaults"
    mysql -u root -p -e "CREATE USER smartkeg IDENTIFIED BY 'Isingthepraisesofbeer!'; source smartkeg/static/sql/build.sql; source smartkeg/static/sql/data.sql;"

fi

echo -e "\n${BLUE}=>${RESET} Configuring System\n"
echo -e "\tMove files"
sudo cp -r smartkeg/ /usr/local/src/

echo -e "\tCreate service files"
sudo echo -e "[Unit]\nDescription=Smartkeg\nRequires=mysqld.service\n\n[Service]\nType=simple\nExecStart=/usr/bin/env python2 /usr/local/src/smartkeg/main.py\n\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/smartkeg.service
sudo echo -e "[Unit]\nDescription=Smartkeg Web Server\nRequires=smartkeg.service\n\n[Service]\nType=simple\nExecStart=/usr/bin/env python2 /usr/local/src/smartkeg/http_server.py\n\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/smartkeg-server.service

echo -e "\tReload Service Daemons"
sudo systemctl daemon-reload

echo -e "\n${BOLD}Done!${RESET}"

